README.md
evalai/auth.py
evalai/challenges.py
evalai/main.py
evalai/submissions.py
evalai/teams.py
setup.py

This is just the general structure of the code which is to get a bearing while working. I'll update with docs and helper function as I finish each feature.

Defining the directory structure for the CLI.

---

scripts/tools/fetch_pull_request

@deshraj Please review the PR.

Add script to fetch pull request

---

evalai/challenges.py
evalai/main.py
evalai/utils/challenges.py
evalai/utils/common.py
evalai/utils/urls.py
tests/data/challenge_response.py
tests/test_challenges.py

Works with https://github.com/Cloud-CV/EvalAI/pull/1685

View participant and host challenges.

---

.github/CONTRIBUTING.md
README.md

Various Templates

---

.coveragerc
.coveralls.yml
.travis.yml
requirements.txt
setup.cfg

Settings for the flake8 and the CI have been referenced from EvalAI.

Travis CI.

---

evalai/utils/auth.py
evalai/utils/challenges.py
evalai/utils/config.py
evalai/utils/urls.py
tests/test_challenges.py

@varunagrawal @deshraj Please review the PR.

Add config file for common variables along with reordering & renaming.

---

evalai/utils/auth.py
evalai/utils/challenges.py
tests/test_auth.py
tests/test_challenges.py
tests/test_requests.py

Increase coverage

---

evalai/challenges.py
evalai/main.py
evalai/teams.py
evalai/utils/config.py
evalai/utils/teams.py
evalai/utils/urls.py
tests/data/teams_response.py
tests/test_requests.py
tests/test_teams.py

```
* evalai teams
* evalai teams create
* evalai challenge CHALLENGE participate TEAM
```

Teams feature

---

evalai/utils/auth.py
evalai/utils/challenges.py
evalai/utils/common.py
tests/data/challenge_response.py
tests/test_auth.py

Fix token dependent error messages.

---

evalai/utils/common.py
evalai/utils/teams.py

Fix issue with token validation

---

evalai/challenges.py
evalai/utils/submissions.py
evalai/utils/urls.py
tests/data/submission_response.py
tests/test_challenges.py
tests/test_requests.py

`evalai challenge CHALLENGE phase PHASE submissions`

User's submission feature.

---

evalai/utils/challenges.py

A small fix to fix error handling.

Fix system exit in challenge phases

---

evalai/challenges.py
evalai/main.py
evalai/submissions.py
evalai/utils/common.py
evalai/utils/submissions.py
evalai/utils/urls.py
tests/data/submission_response.py
tests/test_requests.py
tests/test_submissions.py

This PR covers 
- `evalai challenge CHALLENGE phase PHASE submit FILE`
- `evalai submission SUBMISSION`

Submission feature.

---

evalai/challenges.py
evalai/utils/challenges.py
evalai/utils/urls.py
tests/data/challenge_response.py
tests/test_auth.py
tests/test_challenges.py
tests/test_requests.py

- `evalai challenge CHALLENGE phase PHASE splits`

PhaseSplit feature.

---

evalai/utils/teams.py
tests/test_requests.py
tests/test_teams.py

Teams table fix.

---

evalai/challenges.py
evalai/utils/challenges.py
evalai/utils/urls.py
tests/data/challenge_response.py
tests/test_auth.py
tests/test_challenges.py
tests/test_requests.py

- `evalai challenge CHALLENGE leaderboard CPS`
I used BeautifulTable instead of pytable because this handled overflow much better. I'll add the tests once the design is finalised.

Leaderboard feature.

---

evalai/utils/challenges.py
evalai/utils/common.py
tests/test_challenges.py

Phases formatting fix.

---

evalai/challenges.py
tests/test_requests.py
tests/test_submissions.py

- `evalai challenge 1 phase 2 submit --file result.json`

Add flag for submitting flag

---

evalai/challenges.py
evalai/utils/challenges.py
tests/test_challenges.py

`evalai challenge CHALLENGE phase PHASE --json`

Get phase details as json.

---

evalai/challenges.py
evalai/utils/challenges.py
evalai/utils/urls.py
tests/data/challenge_response.py
tests/test_challenges.py
tests/test_requests.py
tests/test_teams.py

Challenge detail feature.

---

evalai/utils/challenges.py
tests/test_challenges.py

`evalai challenges ongoing`
Fix #78 
Solved #69

Fix ongoing to display only active challenges

---

evalai/challenges.py
evalai/utils/common.py
evalai/utils/submissions.py
tests/data/submission_response.py
tests/test_challenges.py

`evalai challenge CHALLENGE phase PHASE submissions --start-date MM/DD/YY --end-date MM/DD/YY`

Feature to filter submission by date

---

evalai/teams.py
evalai/utils/teams.py
evalai/utils/urls.py
tests/data/teams_response.py
tests/test_requests.py
tests/test_teams.py

- `evalai teams create host` - Create host teams.
- `evalai teams create participant` - Create participant teams.
- `evalai teams --host` - View host teams.
- `evalai teams --participant` - View participant teams.

Feature to view and create host teams

---

tests/base.py
tests/test_auth.py

Fix token reset while running tests

---

evalai/utils/challenges.py
evalai/utils/submissions.py
evalai/utils/teams.py

Bypass the SSL check by turning certificate verifications off. Added `verify=False` to requests.

SSL bypass addition.

---

evalai/get_token.py
evalai/main.py

Fixes #123 
Added a command to get current token . 
Usage `evalai gettoken`

Added command to display the already set token on CLI

---

docs/assets/evalai.css
docs/index.html

Reorder docs page and reorder CLI commands

---

evalai/get_token.py
evalai/utils/auth.py
evalai/utils/common.py

Fixes #130, Remove background color from error messages

Fixes #130, Remove background color from error messages

---

docs/assets/active.js

Fixes #147 .
@RishabhJain2018 Please review and let me know if any changes required 😄

Fix #147: bug while copying command 

---

evalai/set_host.py
evalai/utils/config.py
tests/test_auth.py

Fix #151: Added evalai production url as the default url for fetching details

---

tests/data/challenge_response.py

Changed test data year from `2019` to `2100`. This was causing issue in Unit Tests.
Refer https://github.com/Cloud-CV/evalai-cli/pull/167 for issue.

Unit Test: Forwarded Date for the ongoing challenges in the Test data

---

README.md

Added instructions for installation using `pip install evalai`.

Doc: Add Installation instructions using Pip

---

docs/index.html
evalai/add_token.py

I came upon this problem when I was testing the CLI on my Mac. I saw the errors that was happening due to an invalid command, and immediately told one of the staff about this and asked if I should make a PR about it. They told me that I could.
A friend of mine saw my suggestion for a PR and told me that when I would write the PR, they asked for me to reference their issue that they has opened previously (their issue: #204).

Addressed #204: Update site with newer commands

---

tests/test_get_token.py

**Changes**:
- Add test cases for `get_token` command.
P.S. This PR is to offset the coverage decrease at #263.

Add tests for get_token

---

evalai/utils/common.py
tests/test_add_token.py

**Changes**:
- Add test cases for `set_token` command.
- Add a helper function that generates a random string.
P.S. This PR is to offset the coverage decrease at #263.

Add tests for add_token

---

.coveragerc

Fix #262
The code coverage is decreasing as expected. Of course, the build isn't passing but we need to merge this change.
@vkartik97 @RishabhJain2018 @Ram81 @yashdusing
Could you take a look at this? Thanks in advance!

Fix #262: Make command functions checked by code coverage

---

tests/test_submissions.py

[**The corresponding GCI task**](https://codein.withgoogle.com/dashboard/task-instances/5117769981362176/)
**Changes**:
- Add tests for `push` command.

Add unit tests for evalai push command

---

tests/data/challenge_response.py
tests/data/submission_response.py

The JSON response data stored in `tests/data/` were formatted differently from one to another.
In this PR, I reformatted those data in a consistent way.

Reformat response data in a consistent way

---

tests/test_requests.py

Added tests to make sure output is proper on success

Added tests for Request utils

---

evalai/challenges.py
evalai/utils/challenges.py
evalai/utils/common.py
evalai/utils/submissions.py
evalai/utils/urls.py

Add support for uploading large files.

Add feature to upload large submisison and annotation files.

---

setup.py

Update version from 1.3.1 to 1.3.2

---

evalai/challenges.py

Pass `is_public` flag as json string from cli to handle changes from commit [94ebdb726ffa5f41a01567ad593b6590231abd5ehttps](https://github.com/Cloud-CV/EvalAI/commit/94ebdb726ffa5f41a01567ad593b6590231abd5e)

Pass is_public flag as json string

---

evalai/submissions.py
evalai/utils/requests.py

This PR adds changes to allow making submissions private/public using `--public` `--private` flags to `evalai push` command.

Add public/private flag in evalai push command

---

.travis.yml

Fixes failing coveralls build. Refer this [issue](https://github.com/nedbat/coveragepy/issues/916)

Update coverage version to 5.0.3

---

evalai/utils/urls.py

[BugFix] Multipart upload complete URL fix

---

evalai/utils/common.py
tests/test_submissions.py

Make get_annotation_presigned_url POST request

---

setup.py

Update to version 1.3.6

---

setup.py

Update to version 1.3.7

---

docs/index.html

Add documentation for large submission command and private submission

---

setup.py

Update to version 1.3.8

---

evalai/utils/auth.py
evalai/utils/urls.py

This change replaces the expiring auth token with jwt access token to avoid token expiry on logout.
This PR adds -

Replace expiring auth token with access token

---

setup.py

Update to version 1.3.9

---

setup.py

Update version to 1.3.10

---

.travis.yml
evalai/add_token.py
setup.py
tests/test_add_token.py

Fix travis build and update version

---

setup.py

Update version to 1.3.12

---

setup.py

Update version to 1.3.13

---

.travis.yml

Fixes production [build issue](https://app.travis-ci.com/github/Cloud-CV/evalai-cli/builds/248068934#L404)

Upgrade travis config to python 3.7

---

evalai/submissions.py
evalai/utils/config.py
tests/data/challenge_response.py

This PR removes hardcoded AWS region from EvalAI CLI.

[BugFix] Remove hardcoded AWS region

---

requirements.txt

IMPORTANT NOTES (please read, then delete):
The PR title should start with "Fix #bugnum: " (if applicable), followed by a clear one-line present-tense summary of the changes introduced in the PR. For example: "Fix #bugnum: Introduce the first version of the collection editor.".
Please make sure to mention "#bugnum" somewhere in the description of the PR. This enables Github to link the PR to the corresponding bug.
Please also make sure to follow the [style rules](https://github.com/Cloud-CV/evalai-cli/blob/master/.github/CONTRIBUTING.md).

Add specific urllib3 to requirements

---

.travis.yml
requirements.txt

Reverts Cloud-CV/evalai-cli#352

Add urllib3 requirements

---

.travis.yml

IMPORTANT NOTES (please read, then delete):
The PR title should start with "Fix #bugnum: " (if applicable), followed by a clear one-line present-tense summary of the changes introduced in the PR. For example: "Fix #bugnum: Introduce the first version of the collection editor.".
Please make sure to mention "#bugnum" somewhere in the description of the PR. This enables Github to link the PR to the corresponding bug.
Please also make sure to follow the [style rules](https://github.com/Cloud-CV/evalai-cli/blob/master/.github/CONTRIBUTING.md).

[BugFix] Update to Python 3.11 for travis build

---

evalai/submissions.py

This PR:
- Fixes the error from failing travis build: [Travis Build](https://app.travis-ci.com/github/Cloud-CV/evalai-cli/builds/272028190#L325)

Fix Travis Build
