Cloud-CV/evalai-cli

evalai/challenges.py
evalai/utils/auth.py
evalai/utils/challenges.py
evalai/utils/common.py
tests/data/challenge_response.py
tests/test_challenges.py

Fixes #25
Fixes #45 
The major changes that this PR takes into account is:
1. Add commands for displaying the past, ongoing, future, all challenge data.
2. Add commands for displaying the hosted & participated challenges by a user.
Commands: 
```
- evalai challenges
- evalai challenges ongoing
- evalai challenges past
- evalai challenges future
- evalai challenges --host
- evalai challenges --participant
- evalai challenges --host --participant
```
3. Modified the function names along with variables and removed the redundant code.

Display challenge data along with renaming function & variable names

---

evalai/challenges.py
evalai/utils/challenges.py
evalai/utils/teams.py
evalai/utils/urls.py
tests/data/challenge_response.py
tests/test_challenges.py
tests/test_requests.py

```
evalai challenge CHALLENGE phases
evalai challenge CHALLENGE phase PHASE
```

Phases feature

---

evalai/challenges.py
evalai/utils/submissions.py
tests/test_requests.py
tests/test_submissions.py

```
(venv) isht3@Miller:~/evalai-cli$ evalai challenge 1 phase 2 submit README.md
Do you want to include the Submissions Metadata? [y/N]: N
Your file README.md with the ID 16 is successfully submitted.
You can use `evalai submission 16` to view this submission's status.
```
```
(venv) isht3@Miller:~/evalai-cli$ evalai challenge 1 phase 2 submit README.md
Do you want to include the Submissions Metadata? [y/N]: y
Method Name: test
Method Description: test
Project URL: test
Publication URL: test
Your file README.md with the ID 17 is successfully submitted.
You can use `evalai submission 17` to view this submission's status.
```

Add support for inputting submission metadata

---

evalai/utils/common.py

> Noticed [this](https://github.com/Cloud-CV/evalai-cli/blob/5bc56718520c381f0e1710d9ece4fb2c5bc05449/evalai/utils/challenges.py#L233) function expects a return `data` which [this](https://github.com/Cloud-CV/evalai-cli/blob/5bc56718520c381f0e1710d9ece4fb2c5bc05449/evalai/utils/common.py#L69) function never returns 🙈
As per the discussion on [this](https://github.com/Cloud-CV/evalai-cli/pull/99#issuecomment-416816569) thread. I've added a `return` statement.
@RishabhJain2018 @isht3 please review 😄

add missing return statement

---

.coveragerc
evalai/add_token.py
evalai/main.py
evalai/utils/config.py

GCI Task: Login in CLI using API Authentication Token String
- Adds a `token` argument that can be used to save the EvalAI token.
- Validates the token and checks whether the token is of the right length.
- Tokens can be added or updated using the `$ evalai token <your_token>` command
Please review @RishabhJain2018 @vkartik97

GCI: Login in CLI using API Authentication Token String

---

README.md

Fixes #93 .
Updated ReadME with a badge for our new [docs](https://evalai-cli.cloudcv.org) page.
@RishabhJain2018

Add badge for docs

---

evalai/login.py
evalai/main.py
evalai/utils/auth.py
evalai/utils/urls.py

Added command for Logging into EvalAI using CLI

---

evalai/submissions.py
evalai/utils/submissions.py
tests/data/submission_response.py
tests/test_submissions.py

Added command to display the submission result by passing the submission ID
Deliverables:
Example:
```sh
$ evalai submission 12 result
↪ [{'Total': 60, 'Metric1': 61, 'Metric2': 62, 'Metric3': 63}]
```

Add command to display the submission result in terminal

---

evalai/add_token.py
evalai/teams.py
evalai/utils/auth.py
evalai/utils/challenges.py
evalai/utils/requests.py
evalai/utils/submissions.py
evalai/utils/teams.py

Changes
I used the following colors for the CLI output:
red for errors
yellow for questions
white for information responses
green for success messages
I changed it for all output messages in the EvalAI CLI

UPDATED: Make Output Color Across The CLI Messages Consistent According To Convention

---

tests/test_teams.py

**Changes**:
- Add a test case to check the behavior of `teams` command with both flags given.
P.S. This PR is made to offset [the rightful code coverage decrease](https://coveralls.io/builds/28188927/source?filename=evalai%2Fteams.py#L25) at https://github.com/Cloud-CV/evalai-cli/pull/263

Add tests for teams

---

evalai/add_token.py
evalai/get_token.py

Changes proposed:
* Make import ordering consistent in get_token.py (where `import json` line came after the third-party and `from`-style imports).
* As the ordering was not according to [PEP 8](https://www.python.org/dev/peps/pep-0008/#imports) I made some sample changes to see the differences clearly. 
* In addition to PEP 8, I used [Google's style guide](https://google.github.io/styleguide/pyguide.html#313-imports-formatting) for extended conventions.
The syntax PEP 8 recommends is: 
>  Imports should be grouped in the following order:
>  1. Standard library imports.
>  2. Related third party imports.
>  3. Local application/library specific imports.
>
> You should put a blank line between each group of imports.
So for example,
```python
import os
import sys
from datetime import …
```

Make import ordering consistent

---

evalai/utils/submissions.py

I fixed the typos I could find in the docstrings for EvalAI-cli.
@Ram81 @vkartik97 @RishabhJain2018  @pushkalkatara @Sanji515 @yashdusing
Please take a look

Fixed typos in docstrings

---

evalai/challenges.py

This PR adds changes to allow making submissions private/public while making a submission using `--public``--private` flags
EvalAI Backend PR -- https://github.com/Cloud-CV/EvalAI/pull/3014

Add make submission public/private while submitting

---

.travis.yml

This PR adds `PyYaml` install explicitly to fix coveralls step in travis build. See this issue for reference https://github.com/coveralls-clients/coveralls-python/issues/99.

Fix pyyaml install for coverall

---

docs/index.html
evalai/set_host.py
evalai/utils/config.py
setup.py
tests/test_auth.py

Migrate evalai to eval.ai

---

CNAME

Update CLI docs to cli.eval.ai

---

.coveragerc
.travis.yml
setup.py

Ignore `.eggs` folder from coverage check. See this [report](https://coveralls.io/builds/34361516) for reference.

Ignore .eggs folder while running coveralls coverage

---

evalai/utils/common.py
evalai/utils/urls.py
requirements.txt
tests/data/challenge_response.py
tests/test_submissions.py

This PR uses S3 multipart upload for large file uploaded using `--large` flags. It will allow us to show upload progress using progress bars. EvalAI backend [PR](https://github.com/Cloud-CV/EvalAI/pull/3052)

Add presigned url multi part upload 

---

README.md

[BugFix] EvalAI cli document link

---

requirements.txt
setup.py

Updates requirement constraints for boto3 and tqdm to `>=1.9.88` and `>=4.49.0`. Fixes #300

Update boto3 and tqdm requirement constraints

---

deploy-staging.sh

Downgrades keyring version to fix staging deployment issue. Refer [this](https://travis-ci.community/t/cant-deploy-to-pypi-anymore-pkg-resources-contextualversionconflict-importlib-metadata-0-18/10494/6)

Fix deployment dependency issue

---

evalai/utils/config.py

Set `LEN_OF_TOKEN` to 210 as the jwt token length is 210.

Increase token length limit to 210

---

evalai/add_token.py
tests/test_add_token.py

This PR removes the token length limit checks from `set_token` command, as jwt tokens can have variable length and adding validations for token size < 7kb would be difficult.

Remove token limit checks from set_token command

---

evalai/add_token.py
evalai/challenges.py
evalai/utils/submissions.py
tests/data/challenge_response.py
tests/test_add_token.py
tests/test_requests.py
tests/test_submissions.py

Fixes #305 by adding a feature to allow users to provide metadata along with making submissions from the cli. When a user makes a submission, a request is made to the server to check if any submission_meta_attributes are available for the corresponding challenge_phase. If any attributes are found, a prompt would appear asking the user if he/she wants to submit the values. The user can agree to submit these values and then fill in their corresponding choice for each field prompted. Enough instructions and choices are provided to the user through the prompts too

Fix #305: Allow users to add submission metadata from cli

---

evalai/challenges.py

resolves #318 by changing the format of metadata submitted while making a new submission to make it consistent with metadata saved when submission is made using the frontend.
Earlier metadata format:
```json
[{"TextAttribute": "test"}, {"SingleOptionAttribute": "A"}, {"MultipleChoiceAttribute": ["alpha"]}, {"TrueFalseField": true}]
```
New metadata format:
```json
[{"name": "TextAttribute", "type": "text", "value": "test", "required": null, "description": "Sample"}, {"name": "SingleOptionAttribute", "type": "radio", "value": "A", "options": ["A", "B", "C"], "required": null, "description": "Sample"}, {"name": "MultipleChoiceAttribute", "type": "checkbox", "values": ["alpha", "beta"], "options": ["alpha", "beta", "gamma"], "required": null, "description": "Sample"}, {"name": …
```

Fix #318: Change format for submitting meta on new submission

---

evalai/utils/common.py

Handle submission upload failure SQS message

---

.travis.yml

Reverts Cloud-CV/evalai-cli#356

Revert "Use Ubuntu 22.04 for Travis Build"

---

requirements.txt

Specified and downgrade the urllib3 version to 1.25.11 to be compatible with OpenSSL 1.1.1 +

Fix OpenSSL issue

---

requirements.txt

Reverts Cloud-CV/evalai-cli#366

Revert "Fix OpenSSL issue"
